[package]
name = "demo"
version = "0.0.1"
edition = "2021"

[dependencies]
discord_interaction = { path = "../.." }
lambda_http = "0.8.1"
regex = "1.10.2"
tokio = { version = "1", features = ["macros"] }

