name: Main

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:

    runs-on: ubuntu-latest
    environment: Publish
    env:
      UPDATE_CRATE_KEY: ${{ secrets.UPDATE_CRATE_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: RunPublish
      run: cargo publish --token ${UPDATE_CRATE_KEY}
 
