name: Global

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  FormatBuildTest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check Formatting
      run: cargo fmt --check
    - name: Build Lib
      run: cargo build --verbose
    - name: Test Lib
      run: cargo test --verbose
      
